apiVersion: apps/v1
kind: Deployment
metadata:
  name: vblog
spec:
  replicas: 1
  selector:
    matchLabels:
        app: vblog
  template:
    metadata:
      labels:
        app: vblog
    spec:
      containers:
      - name: vblog
        image: 192.168.132.12:85/vblog/blogserver:latest
        ports:
        - containerPort: 8081
